version: "3.8"

services:
  db:
    image: postgres:15
    container_name: gymor-db
    environment:
      POSTGRES_DB: gymor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: gymor-api
    container_name: gymor-api
    depends_on:
      - db
    environment:
        SPRING_PROFILES_ACTIVE: prod
    DB_URL: jdbc:postgresql://db:5432/gymor
    DB_USER: gymor
    DB_PASS: gymor123
    JWT_SECRET: mySuperSecretKeyForJwtThatIsAtLeast32Chars!!
    CORS_ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8080:8080"

volumes:
  pgdata: