services:
  db:
    image: postgres:15
    container_name: gymor-db
    restart: always
    environment:
      POSTGRES_DB: gymor
      POSTGRES_USER: gymor
      POSTGRES_PASSWORD: gymor123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: gymor-api
    container_name: gymor-api
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://db:5432/gymor
      DB_USER: gymor
      DB_PASS: gymor123
      JWT_SECRET: mySuperSecretKeyForJwtThatIsAtLeast32Chars!!
      CORS_ALLOWED_ORIGINS: http://localhost:3000

volumes:
  postgres_data: