spring:
  profiles:
    active: local  # ← Perfil por defecto

  # Configuración JPA general
  jpa:
    open-in-view: false  # Evita lazy loading fuera de transacciones

# Logging general
logging:
  level:
    ApiGymorEjecucion.Api: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Valor por defecto para CORS (se sobrescribe en cada perfil)
app:
  cors:
    allowed-origins: "http://localhost:8080"
